import Head from 'next/head'
import { FormEvent, useState } from "react";
import { Container } from "@/components/Container";
import { PlayerStats } from "@/components/Player/PlayerStats";
import { Player } from "@/types/player.interface";
import { Skills } from "@/types/player.interface";
import styles from '@/styles/Home.module.css'

export default function Home() {
    const [username, setUsername] = useState<string>("");
    const [player, setPlayer] = useState<Player | null>(null);
    const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        const res = await fetch(`/api/hiscores?username=${username}`);
        const data: Player = await res.json();
        setPlayer(data);
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container>
                <h1 className={styles.hiscoresHeader}>Fetch from hiscores</h1>
                <form onSubmit={handleSubmit} className={styles.hiscoresForm}>
                    <label htmlFor="username" className={"visuallyHidden"}>Username</label>
                    <input
                        placeholder="Username"
                        className={styles.hiscoresInput}
                        type="text"
                        id="username"
                        value={username}
                        onChange={(e) => setUsername(e.target.value)}
                        aria-label="Username"
                    />
                    <button type="submit" className={styles.hiscoresButton}>Lookup</button>
                </form>
                <PlayerStats skills={player?.skills || {} as Partial<Skills>} />
            </Container>
        </>
    )
}
